name: Go CI
on:
  - push
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - run: go test ./...
